# Site settings
title: "The Indispensables Co."
description: "The essentials of modern life you simply can't afford not having."
baseurl_en: "/introuvables/en" # the subpath of your site, e.g. /blog/
baseurl_fi: "/introuvables/fi"
baseurl: "/introuvables"
url: "http://leolobski.github.io" # the base hostname & protocol for your site
copyright: '&copy; 2018 Elisa Leppänen & Leo Lobski'

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

